INSERT INTO core.dim_carrier (
    mcs150_date,
    add_date,
    status_code,
    dot_number,
    dun_bradstreet_no,
    phy_omc_region,
    safety_inv_terr,
    carrier_operation,
    business_org_id,
    mcs150_mileage,
    mcs150_mileage_year,
    mcs151_mileage,
    total_cars,
    mcs150_update_code_id,
    prior_revoke_flag,
    prior_revoke_dot_number,
    phone,
    fax,
    cell_phone,
    company_officer_1,
    company_officer_2,
    business_org_desc,
    truck_units,
    power_units,
    bus_units,
    fleetsize,
    review_id,
    recordable_crash_rate,
    mail_nationality_indicator,
    phy_nationality_indicator,
    phy_barrio,
    mail_barrio,
    carship,
    docket1prefix,
    docket1,
    docket2prefix,
    docket2,
    docket3prefix,
    docket3,
    pointnum,
    total_intrastate_drivers,
    mcsipstep,
    mcsipdate,
    hm_ind,
    interstate_beyond_100_miles,
    interstate_within_100_miles,
    intrastate_beyond_100_miles,
    intrastate_within_100_miles,
    total_cdl,
    total_drivers,
    avg_drivers_leased_per_month,
    classdef,
    legal_name,
    dba_name,
    phy_street,
    phy_city,
    phy_country,
    phy_state,
    phy_zip,
    phy_cnty,
    carrier_mailing_street,
    carrier_mailing_state,
    carrier_mailing_city,
    carrier_mailing_country,
    carrier_mailing_zip,
    carrier_mailing_cnty,
    carrier_mailing_und_date,
    driver_inter_total,
    email_address,
    review_type,
    review_date,
    safety_rating,
    safety_rating_date,
    undeliv_phy,
    crgo_genfreight,
    crgo_household,
    crgo_metalsheet,
    crgo_motoveh,
    crgo_drivetow,
    crgo_logpole,
    crgo_bldgmat,
    crgo_mobilehome,
    crgo_machlrg,
    crgo_produce,
    crgo_liqgas,
    crgo_intermodal,
    crgo_passengers,
    crgo_oilfield,
    crgo_livestock,
    crgo_grainfeed,
    crgo_coalcoke,
    crgo_meat,
    crgo_garbage,
    crgo_usmail,
    crgo_chem,
    crgo_drybulk,
    crgo_coldfood,
    crgo_beverages,
    crgo_paperprod,
    crgo_utility,
    crgo_farmsupp,
    crgo_construct,
    crgo_waterwell,
    crgo_cargoothr,
    crgo_cargoothr_desc,
    owntruck,
    owntract,
    owntrail,
    owncoach,
    ownschool_1_8,
    ownschool_9_15,
    ownschool_16,
    ownbus_16,
    ownvan_1_8,
    ownvan_9_15,
    ownlimo_1_8,
    ownlimo_9_15,
    ownlimo_16,
    trmtruck,
    trmtract,
    trmtrail,
    trmcoach,
    trmschool_1_8,
    trmschool_9_15,
    trmschool_16,
    trmbus_16,
    trmvan_1_8,
    trmvan_9_15,
    trmlimo_1_8,
    trmlimo_9_15,
    trmlimo_16,
    trptruck,
    trptract,
    trptrail,
    trpcoach,
    trpschool_1_8,
    trpschool_9_15,
    trpschool_16,
    trpbus_16,
    trpvan_1_8,
    trpvan_9_15,
    trplimo_1_8,
    trplimo_9_15,
    trplimo_16,
    docket1_status_code,
    docket2_status_code,
    docket3_status_code
)
SELECT
    -- DATE parsing logic (same as your old insert)
    CASE
        WHEN mcs150_date ~ '^[0-9]{8}(\.0)?$' THEN
            to_date(regexp_replace(mcs150_date, '\.0$', ''), 'YYYYMMDD')
        WHEN mcs150_date ~ '^\d{4}-\d{2}-\d{2}$' THEN
            mcs150_date::date
        ELSE NULL
    END AS mcs150_date,

    -- Add date as staging add_date, use same logic
    CASE
        WHEN add_date ~ '^[0-9]{8}(\.0)?$' THEN
            to_date(regexp_replace(add_date, '\.0$', ''), 'YYYYMMDD')
        WHEN add_date ~ '^\d{4}-\d{2}-\d{2}$' THEN
            add_date::date
        ELSE NULL
    END AS add_date,

    NULLIF(status_code, ''),
    NULLIF(regexp_replace(dot_number, '\.0$', ''), '')::bigint,
    NULLIF(dun_bradstreet_no, ''),
    NULLIF(phy_omc_region, '')::numeric,
    NULLIF(safety_inv_terr, ''),
    NULLIF(carrier_operation, ''),
    NULLIF(business_org_id, ''),
    NULLIF(mcs150_mileage, '')::numeric,
    NULLIF(mcs150_mileage_year, '')::numeric,
    NULLIF(mcs151_mileage, '')::numeric,
    NULLIF(total_cars, '')::numeric,
    NULLIF(mcs150_update_code_id, ''),
    NULLIF(prior_revoke_flag, ''),
    NULLIF(prior_revoke_dot_number, ''),
    NULLIF(phone, ''),
    NULLIF(fax, ''),
    NULLIF(cell_phone, ''),
    NULLIF(company_officer_1, ''),
    NULLIF(company_officer_2, ''),
    NULLIF(business_org_desc, ''),

    NULLIF(truck_units, '')::numeric,
    NULLIF(power_units, '')::numeric,
    NULLIF(bus_units, '')::numeric,
    NULLIF(fleetsize, ''),
    NULLIF(review_id, '')::numeric,
    NULLIF(recordable_crash_rate, '')::numeric,
    NULLIF(mail_nationality_indicator, ''),
    NULLIF(phy_nationality_indicator, ''),
    NULLIF(phy_barrio, ''),
    NULLIF(mail_barrio, ''),
    NULLIF(carship, ''),
    NULLIF(docket1prefix, ''),
    NULLIF(docket1, '')::numeric,
    NULLIF(docket2prefix, ''),
    NULLIF(docket2, '')::numeric,
    NULLIF(docket3prefix, ''),
    NULLIF(docket3, '')::numeric,
    NULLIF(pointnum, ''),
    NULLIF(total_intrastate_drivers, '')::numeric,
    NULLIF(mcsipstep, '')::numeric,
    NULLIF(mcsipdate, ''),
    NULLIF(hm_ind, ''),
    NULLIF(interstate_beyond_100_miles, '')::numeric,
    NULLIF(interstate_within_100_miles, '')::numeric,
    NULLIF(intrastate_beyond_100_miles, '')::numeric,
    NULLIF(intrastate_within_100_miles, '')::numeric,
    NULLIF(total_cdl, '')::numeric,
    NULLIF(total_drivers, '')::numeric,
    NULLIF(avg_drivers_leased_per_month, '')::numeric,
    NULLIF(classdef, ''),
    NULLIF(legal_name, ''),
    NULLIF(dba_name, ''),
    NULLIF(phy_street, ''),
    NULLIF(phy_city, ''),
    NULLIF(phy_country, ''),
    NULLIF(phy_state, ''),
    NULLIF(phy_zip, ''),
    NULLIF(phy_cnty, ''),
    NULLIF(carrier_mailing_street, ''),
    NULLIF(carrier_mailing_state, ''),
    NULLIF(carrier_mailing_city, ''),
    NULLIF(carrier_mailing_country, ''),
    NULLIF(carrier_mailing_zip, ''),
    NULLIF(carrier_mailing_cnty, ''),
    NULLIF(carrier_mailing_und_date, ''),
    NULLIF(driver_inter_total, ''),
    NULLIF(email_address, ''),
    NULLIF(review_type, ''),
    NULLIF(review_date, ''),
    NULLIF(safety_rating, ''),
    NULLIF(safety_rating_date, ''),
    NULLIF(undeliv_phy, ''),
    NULLIF(crgo_genfreight, ''),
    NULLIF(crgo_household, ''),
    NULLIF(crgo_metalsheet, ''),
    NULLIF(crgo_motoveh, ''),
    NULLIF(crgo_drivetow, ''),
    NULLIF(crgo_logpole, ''),
    NULLIF(crgo_bldgmat, ''),
    NULLIF(crgo_mobilehome, ''),
    NULLIF(crgo_machlrg, ''),
    NULLIF(crgo_produce, ''),
    NULLIF(crgo_liqgas, ''),
    NULLIF(crgo_intermodal, ''),
    NULLIF(crgo_passengers, ''),
    NULLIF(crgo_oilfield, ''),
    NULLIF(crgo_livestock, ''),
    NULLIF(crgo_grainfeed, ''),
    NULLIF(crgo_coalcoke, ''),
    NULLIF(crgo_meat, ''),
    NULLIF(crgo_garbage, ''),
    NULLIF(crgo_usmail, ''),
    NULLIF(crgo_chem, ''),
    NULLIF(crgo_drybulk, ''),
    NULLIF(crgo_coldfood, ''),
    NULLIF(crgo_beverages, ''),
    NULLIF(crgo_paperprod, ''),
    NULLIF(crgo_utility, ''),
    NULLIF(crgo_farmsupp, ''),
    NULLIF(crgo_construct, ''),
    NULLIF(crgo_waterwell, ''),
    NULLIF(crgo_cargoothr, ''),
    NULLIF(crgo_cargoothr_desc, ''),
    NULLIF(owntruck, '')::numeric,
    NULLIF(owntract, '')::numeric,
    NULLIF(owntrail, '')::numeric,
    NULLIF(owncoach, '')::numeric,
    NULLIF(ownschool_1_8, '')::numeric,
    NULLIF(ownschool_9_15, '')::numeric,
    NULLIF(ownschool_16, '')::numeric,
    NULLIF(ownbus_16, '')::numeric,
    NULLIF(ownvan_1_8, '')::numeric,
    NULLIF(ownvan_9_15, '')::numeric,
    NULLIF(ownlimo_1_8, '')::numeric,
    NULLIF(ownlimo_9_15, '')::numeric,
    NULLIF(ownlimo_16, '')::numeric,
    NULLIF(trmtruck, '')::numeric,
    NULLIF(trmtract, '')::numeric,
    NULLIF(trmtrail, '')::numeric,
    NULLIF(trmcoach, '')::numeric,
    NULLIF(trmschool_1_8, '')::numeric,
    NULLIF(trmschool_9_15, '')::numeric,
    NULLIF(trmschool_16, '')::numeric,
    NULLIF(trmbus_16, '')::numeric,
    NULLIF(trmvan_1_8, '')::numeric,
    NULLIF(trmvan_9_15, '')::numeric,
    NULLIF(trmlimo_1_8, '')::numeric,
    NULLIF(trmlimo_9_15, '')::numeric,
    NULLIF(trmlimo_16, '')::numeric,
    NULLIF(trptruck, '')::numeric,
    NULLIF(trptract, '')::numeric,
    NULLIF(trptrail, '')::numeric,
    NULLIF(trpcoach, '')::numeric,
    NULLIF(trpschool_1_8, '')::numeric,
    NULLIF(trpschool_9_15, '')::numeric,
    NULLIF(trpschool_16, '')::numeric,
    NULLIF(trpbus_16, '')::numeric,
    NULLIF(trpvan_1_8, '')::numeric,
    NULLIF(trpvan_9_15, '')::numeric,
    NULLIF(trplimo_1_8, '')::numeric,
    NULLIF(trplimo_9_15, '')::numeric,
    NULLIF(trplimo_16, '')::numeric,
    NULLIF(docket1_status_code, ''),
    NULLIF(docket2_status_code, ''),
    NULLIF(docket3_status_code, '')
FROM staging.motor_carrier_census_raw;
    