INSERT INTO core.fact_inspection (
    inspection_id,
    dot_number,
    change_date,
    report_state,
    report_number,
    insp_date,
    insp_start_time,
    insp_end_time,
    registration_date,
    region,
    ci_status_code,
    location,
    location_desc,
    county_code_state,
    county_code,
    insp_level_id,
    service_center,
    census_source_id,
    insp_facility,
    shipper_name,
    shipping_paper_number,
    cargo_tank,
    hazmat_placard_req,
    snet_version_number,
    snet_search_date,
    alcohol_control_sub,
    drug_intrdctn_search,
    drug_intrdctn_arrests,
    size_weight_enf,
    traffic_enf,
    local_enf_jurisdiction,
    pen_cen_match,
    final_status_date,
    post_acc_ind,
    gross_comb_veh_wt,
    viol_total,
    oos_total,
    driver_viol_total,
    driver_oos_total,
    vehicle_viol_total,
    vehicle_oos_total,
    hazmat_viol_total,
    hazmat_oos_total,
    snet_sequence_id,
    transaction_code,
    transaction_date,
    upload_date,
    upload_first_byte,
    upload_dot_number,
    upload_search_indicator,
    census_search_date,
    snet_input_date,
    source_office,
    mcmis_add_date,
    insp_carrier_name,
    insp_carrier_street,
    insp_carrier_city,
    insp_carrier_state,
    insp_carrier_zip_code,
    insp_colonia,
    docket_number,
    insp_interstate
)
SELECT
    NULLIF(regexp_replace(inspection_id, '\.0$', ''), '')::numeric,
    NULLIF(regexp_replace(dot_number, '\.0$', ''), '')::bigint,
    NULLIF(BTRIM(regexp_replace(change_date, '\.0$', '')), ''),
    NULLIF(report_state, ''),
    NULLIF(report_number, ''),
    NULLIF(BTRIM(regexp_replace(insp_date, '\.0$', '')), ''),
    NULLIF(BTRIM(regexp_replace(insp_start_time, '\.0$', '')), ''),
    NULLIF(BTRIM(regexp_replace(insp_end_time, '\.0$', '')), ''),
    NULLIF(BTRIM(regexp_replace(registration_date, '\.0$', '')), ''),
    NULLIF(region, ''),
    NULLIF(ci_status_code, ''),
    NULLIF(location, ''),
    NULLIF(location_desc, ''),
    NULLIF(county_code_state, ''),
    NULLIF(county_code, ''),
    NULLIF(regexp_replace(insp_level_id, '\.0$', ''), '')::numeric,
    NULLIF(service_center, ''),
    NULLIF(regexp_replace(census_source_id, '\.0$', ''), '')::numeric,
    NULLIF(insp_facility, ''),
    NULLIF(shipper_name, ''),
    NULLIF(shipping_paper_number, ''),
    NULLIF(cargo_tank, ''),
    NULLIF(hazmat_placard_req, ''),
    NULLIF(snet_version_number, ''),
    NULLIF(BTRIM(regexp_replace(snet_search_date, '\.0$', '')), ''),
    NULLIF(alcohol_control_sub, ''),
    NULLIF(drug_intrdctn_search, ''),
    NULLIF(regexp_replace(drug_intrdctn_arrests, '\.0$', ''), '')::numeric,
    NULLIF(size_weight_enf, ''),
    NULLIF(traffic_enf, ''),
    NULLIF(local_enf_jurisdiction, ''),
    NULLIF(pen_cen_match, ''),
     NULLIF(BTRIM(regexp_replace(final_status_date, '\.0$', '')), ''),
    NULLIF(post_acc_ind, ''),
    NULLIF(gross_comb_veh_wt, ''),
    NULLIF(regexp_replace(viol_total, '\.0$', ''), '')::numeric,
    NULLIF(regexp_replace(oos_total, '\.0$', ''), '')::numeric,
    NULLIF(regexp_replace(driver_viol_total, '\.0$', ''), '')::numeric,
    NULLIF(regexp_replace(driver_oos_total, '\.0$', ''), '')::numeric,
    NULLIF(regexp_replace(vehicle_viol_total, '\.0$', ''), '')::numeric,
    NULLIF(regexp_replace(vehicle_oos_total, '\.0$', ''), '')::numeric,
    NULLIF(regexp_replace(hazmat_viol_total, '\.0$', ''), '')::numeric,
    NULLIF(regexp_replace(hazmat_oos_total, '\.0$', ''), '')::numeric,
    NULLIF(regexp_replace(snet_sequence_id, '\.0$', ''), '')::numeric,
    NULLIF(transaction_code, ''),
    NULLIF(BTRIM(regexp_replace(transaction_date, '\.0$', '')), ''),
    NULLIF(BTRIM(regexp_replace(upload_date, '\.0$', '')), ''),
    NULLIF(upload_first_byte, ''),
    NULLIF(upload_dot_number, ''),
    NULLIF(upload_search_indicator, ''),
    NULLIF(BTRIM(regexp_replace(census_search_date, '\.0$', '')), ''),
    NULLIF(BTRIM(regexp_replace(snet_input_date, '\.0$', '')), ''),
    NULLIF(source_office, ''),
    NULLIF(BTRIM(regexp_replace(mcmis_add_date, '\.0$', '')), ''),
    NULLIF(insp_carrier_name, ''),
    NULLIF(insp_carrier_street, ''),
    NULLIF(insp_carrier_city, ''),
    NULLIF(insp_carrier_state, ''),
    NULLIF(insp_carrier_zip_code, ''),
    NULLIF(insp_colonia, ''),
    NULLIF(regexp_replace(docket_number, '\.0$', ''), '')::numeric,
    NULLIF(insp_interstate, '')
FROM staging.vehicle_inspection_file_raw;
