INSERT INTO core.fact_crash (
    crash_id,
    dot_number,
    change_date,
    report_state,
    report_number,
    report_date,
    report_time,
    report_seq_no,
    ci_status_code,
    final_status_date,
    location,
    city_code,
    city,
    state,
    county_code,
    truck_bus_ind,
    trafficway_id,
    access_control_id,
    road_surface_condition_id,
    cargo_body_type_id,
    gvw_rating_id,
    vehicle_identification_number,
    vehicle_license_number,
    vehicle_lic_state,
    vehicle_hazmat_placard,
    weather_condition_id,
    vehicle_configuration_id,
    light_condition_id,
    hazmat_released,
    agency,
    vehicles_in_accident,
    fatalities,
    injuries,
    tow_away,
    federal_recordable,
    state_recordable,
    snet_version_number,
    snet_sequence_id,
    transaction_code,
    transaction_date,
    upload_first_byte,
    upload_dot_number,
    upload_search_indicator,
    upload_date,
    add_date,
    crash_carrier_id,
    crash_carrier_name,
    crash_carrier_street,
    crash_carrier_city,
    crash_carrier_city_code,
    crash_carrier_state,
    crash_carrier_zip_code,
    crash_colonia,
    docket_number,
    crash_carrier_interstate,
    no_id_flag,
    state_number,
    state_issuing_number,
    crash_event_seq_id_desc
)
SELECT
    NULLIF(regexp_replace(crash_id, '\.0$', ''), '')::bigint,
    NULLIF(regexp_replace(dot_number, '\.0$', ''), '')::bigint,
    
    NULLIF(BTRIM(regexp_replace(change_date, '\.0$', '')), ''),

    NULLIF(report_state, ''),
    NULLIF(report_number, ''),
    NULLIF(BTRIM(regexp_replace(report_date, '\.0$', '')), ''),
   
    NULLIF(BTRIM(regexp_replace(report_time, '\.0$', '')), ''),
    NULLIF(regexp_replace(report_seq_no, '\.0$', ''), '')::int,
    NULLIF(ci_status_code, ''),
    NULLIF(BTRIM(regexp_replace(final_status_date, '\.0$', '')), ''),
    NULLIF(location, ''),
    NULLIF(city_code, ''),
    NULLIF(city, ''),
    NULLIF(state, ''),
    NULLIF(regexp_replace(county_code, '\.0$', ''), '')::int,
    NULLIF(truck_bus_ind, ''),
    NULLIF(trafficway_id, ''),
    NULLIF(access_control_id, ''),
    NULLIF(road_surface_condition_id, ''),
    NULLIF(cargo_body_type_id, ''),
    NULLIF(gvw_rating_id, ''),
    NULLIF(vehicle_identification_number, ''),
    NULLIF(vehicle_license_number, ''),
    NULLIF(vehicle_lic_state, ''),
    NULLIF(vehicle_hazmat_placard, ''),
    NULLIF(weather_condition_id, ''),
    NULLIF(vehicle_configuration_id, ''),
    NULLIF(light_condition_id, ''),
    NULLIF(hazmat_released, ''),
    NULLIF(agency, ''),
    NULLIF(regexp_replace(vehicles_in_accident, '\.0$', ''), '')::int,
    NULLIF(regexp_replace(fatalities, '\.0$', ''), '')::int,
    NULLIF(regexp_replace(injuries, '\.0$', ''), '')::int,
    NULLIF(tow_away, ''),
    NULLIF(federal_recordable, ''),
    NULLIF(state_recordable, ''),
    NULLIF(snet_version_number, ''),
    NULLIF(snet_sequence_id, ''),
    NULLIF(transaction_code, ''),
    NULLIF(BTRIM(regexp_replace(transaction_date, '\.0$', '')), ''),
    NULLIF(upload_first_byte, ''),
    NULLIF(upload_dot_number, ''),
    NULLIF(upload_search_indicator, ''),
    NULLIF(BTRIM(regexp_replace(upload_date, '\.0$', '')), ''),
    NULLIF(BTRIM(regexp_replace(add_date, '\.0$', '')), ''),
    NULLIF(regexp_replace(crash_carrier_id, '\.0$', ''), '')::bigint,
    NULLIF(crash_carrier_name, ''),
    NULLIF(crash_carrier_street, ''),
    NULLIF(crash_carrier_city, ''),
    NULLIF(crash_carrier_city_code, ''),
    NULLIF(crash_carrier_state, ''),
    NULLIF(crash_carrier_zip_code, ''),
    NULLIF(crash_colonia, ''),
    NULLIF(regexp_replace(docket_number, '\.0$', ''), '')::bigint,
    NULLIF(crash_carrier_interstate,''),
    NULLIF(no_id_flag, ''),
    NULLIF(state_number, ''),
    NULLIF(state_issuing_number, ''),
    NULLIF(crash_event_seq_id_desc, '')
FROM staging.crash_file_raw;
